// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjh8JD0UNuqoRN6GGS1dxRHyVJCU7fdF0',
    appId: '1:177404402107:web:0c06774775794964c9cc9e',
    messagingSenderId: '177404402107',
    projectId: 'coffeeapp-72d2c',
    authDomain: 'coffeeapp-72d2c.firebaseapp.com',
    storageBucket: 'coffeeapp-72d2c.appspot.com',
    measurementId: 'G-S60EH107JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCae-kNjcL0TOm4FSvCw4Pi3zRBRdutqac',
    appId: '1:177404402107:android:b9603aa275bae0fbc9cc9e',
    messagingSenderId: '177404402107',
    projectId: 'coffeeapp-72d2c',
    storageBucket: 'coffeeapp-72d2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8S_LtOb0Nr2mfeJ5M-GtuQowW9XiiWgA',
    appId: '1:177404402107:ios:5a378931266574dfc9cc9e',
    messagingSenderId: '177404402107',
    projectId: 'coffeeapp-72d2c',
    storageBucket: 'coffeeapp-72d2c.appspot.com',
    iosBundleId: 'com.dbvertex.flutterapp',
  );
}
